# Generated by Django 3.1.7 on 2021-06-04 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_canal_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
