# Generated by Django 3.1.7 on 2021-06-09 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_canal_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='title',
        ),
        migrations.AddField(
            model_name='canal',
            name='eliminar_canal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='canal',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajes',
            name='leido',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
