# Generated by Django 3.1.7 on 2021-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210609_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='title',
            field=models.CharField(blank=True, default='conversation', max_length=300, null=True),
        ),
    ]
