# Generated by Django 3.1.7 on 2021-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210609_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
