# Generated by Django 3.1.7 on 2021-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_canal_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='eliminar_canal',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='leido',
        ),
        migrations.AddField(
            model_name='canal',
            name='eliminado_emisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canal',
            name='eliminado_receptor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canal',
            name='leido_emisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canal',
            name='leido_receptor',
            field=models.BooleanField(default=False),
        ),
    ]
