# Generated by Django 3.1.7 on 2021-06-09 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_auto_20210609_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor_canal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canal',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor_canal', to=settings.AUTH_USER_MODEL),
        ),
    ]
