# Generated by Django 3.2 on 2021-06-04 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url_audio', models.FileField(blank=True, null=True, upload_to='user/song')),
            ],
            options={
                'ordering': ('title', 'url_audio'),
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TipoOjeador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url_video', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('title', 'url_video'),
            },
        ),
        migrations.CreateModel(
            name='UserProfileOjeadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profile', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/img')),
                ('descripcion', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('web', models.CharField(blank=True, max_length=300, null=True)),
                ('email_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('canal_mensajes', models.ManyToManyField(blank=True, null=True, to='chat.Canal')),
                ('generos', models.ManyToManyField(to='accounts.Generos')),
                ('noticias', models.ManyToManyField(blank=True, null=True, to='noticias.Noticias')),
                ('provincia_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.provincia')),
                ('tipo_ojeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tipoojeador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileMusicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profile', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/img')),
                ('descripcion', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('web', models.CharField(blank=True, max_length=300, null=True)),
                ('email_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('canal_mensajes', models.ManyToManyField(blank=True, null=True, to='chat.Canal')),
                ('generos', models.ManyToManyField(to='accounts.Generos')),
                ('noticias', models.ManyToManyField(blank=True, null=True, to='noticias.Noticias')),
                ('provincia_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.provincia')),
                ('url_audios', models.ManyToManyField(blank=True, null=True, to='accounts.Audios')),
                ('url_videos', models.ManyToManyField(blank=True, null=True, to='accounts.Videos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
