# Generated by Django 3.1.7 on 2021-04-13 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_audio', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('url_audio',),
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='UserProfileMusicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banda', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='user/imagen')),
                ('informacion', models.TextField()),
                ('twitter', models.CharField(max_length=50, null=True)),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('web', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('generos', models.ManyToManyField(to='accounts.Generos')),
                ('url_audios', models.ManyToManyField(to='accounts.Audios')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('url_video',),
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='userprofilemusicos',
            name='url_videos',
            field=models.ManyToManyField(to='accounts.Videos'),
        ),
        migrations.AddField(
            model_name='userprofilemusicos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
