# Generated by Django 3.1.7 on 2021-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210413_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='url_audio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='facebook',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='instagram',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='twitter',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='web',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='url_video',
            field=models.CharField(max_length=500),
        ),
    ]
