# Generated by Django 3.1.7 on 2021-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210413_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='user/imagen'),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='instagram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='web',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
