# Generated by Django 3.1.7 on 2021-04-13 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20210413_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='url_audios',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Audios'),
        ),
        migrations.AlterField(
            model_name='userprofilemusicos',
            name='url_videos',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Videos'),
        ),
        migrations.CreateModel(
            name='UserProfileOjeadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ojeador', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='user/imagen')),
                ('descripcion', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('web', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('generos', models.ManyToManyField(to='accounts.Generos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
