# Generated by Django 3.1.7 on 2021-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210413_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOjeador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.RenameField(
            model_name='userprofilemusicos',
            old_name='email',
            new_name='email_grupo',
        ),
        migrations.RenameField(
            model_name='userprofileojeadores',
            old_name='email',
            new_name='email_ojeador',
        ),
    ]
