# Generated by Django 3.1.7 on 2021-04-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210413_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileojeadores',
            name='tipo_ojeador',
            field=models.ManyToManyField(to='accounts.TipoOjeador'),
        ),
    ]
