# Generated by Django 3.1.7 on 2021-04-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofileojeadores_tipo_ojeador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoojeador',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofileojeadores',
            name='tipo_ojeador',
        ),
        migrations.AddField(
            model_name='userprofileojeadores',
            name='tipo_ojeador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.tipoojeador'),
            preserve_default=False,
        ),
    ]
