# Generated by Django 3.2 on 2021-04-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210413_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemusicos',
            old_name='imagen',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='userprofileojeadores',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
