# Generated by Django 3.1.7 on 2021-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210423_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ciudades', models.ManyToManyField(to='accounts.Ciudad')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='userprofilemusicos',
            name='ciudad_origen',
            field=models.ManyToManyField(to='accounts.Ciudad'),
        ),
        migrations.AddField(
            model_name='userprofilemusicos',
            name='provincia_origen',
            field=models.ManyToManyField(to='accounts.Provincia'),
        ),
    ]
