# Generated by Django 3.1.7 on 2021-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210502_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='ciudades',
        ),
        migrations.RemoveField(
            model_name='userprofilemusicos',
            name='ciudad_origen',
        ),
        migrations.AddField(
            model_name='userprofileojeadores',
            name='provincia_origen',
            field=models.ManyToManyField(to='accounts.Provincia'),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
