# Generated by Django 3.1.7 on 2021-05-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210503_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemusicos',
            name='provincia_origen',
        ),
        migrations.AddField(
            model_name='userprofilemusicos',
            name='provincia_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.provincia'),
            preserve_default=False,
        ),
    ]
