# Generated by Django 3.1.7 on 2021-05-04 16:40

from django.db import migrations
# import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210503_1930'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='userprofilemusicos',
    #         name='avatar',
    #         field=stdimage.models.JPEGField(blank=True, null=True, upload_to='user/img'),
    #     ),
    # ]
