# Generated by Django 3.1.7 on 2021-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
        ('accounts', '0017_auto_20210504_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemusicos',
            name='noticias',
            field=models.ManyToManyField(blank=True, null=True, to='noticias.Noticias'),
        ),
        migrations.AddField(
            model_name='userprofileojeadores',
            name='noticias',
            field=models.ManyToManyField(blank=True, null=True, to='noticias.Noticias'),
        ),
    ]
