# Generated by Django 3.1.7 on 2021-05-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210515_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemusicos',
            old_name='email_grupo',
            new_name='email_profile',
        ),
        migrations.RenameField(
            model_name='userprofilemusicos',
            old_name='nombre_banda',
            new_name='nombre_profile',
        ),
        migrations.RenameField(
            model_name='userprofileojeadores',
            old_name='email_ojeador',
            new_name='email_profile',
        ),
        migrations.RenameField(
            model_name='userprofileojeadores',
            old_name='nombre_ojeador',
            new_name='nombre_profile',
        ),
    ]
