# Generated by Django 3.1.7 on 2021-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210516_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audios',
            options={'ordering': ('title', 'url_audio')},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ('title', 'url_video')},
        ),
        migrations.AddField(
            model_name='audios',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
