# Generated by Django 3.1.7 on 2021-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210517_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='url_audio',
            field=models.FileField(blank=True, null=True, upload_to='user/song'),
        ),
    ]
