# Generated by Django 3.2 on 2021-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210522_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileojeadores',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/img'),
        ),
    ]
