# Generated by Django 3.1.7 on 2021-05-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userprofileojeadores_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
