# Generated by Django 3.1.7 on 2021-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20210606_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema_foro',
            name='post_foro',
        ),
        migrations.AddField(
            model_name='tema_foro',
            name='post_foro',
            field=models.ManyToManyField(blank=True, null=True, to='foro.Post'),
        ),
    ]
