# Generated by Django 3.1.7 on 2021-06-13 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_auto_20210606_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mensajes_post',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='tema_foro',
            name='title',
            field=models.CharField(max_length=160),
        ),
    ]
